version: "3.8"

services:
  pulumi-bootstrap:
    build:
      context: .
      dockerfile: .devcontainer/dev.Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - .:/workspace:cached
      - projectname-bashhistory:/commandhistory
volumes:
  projectname-bashhistory: